### ISSUE TITLE
InteractionCommandClient Error

### ISSUE THREAD

**Issue by insyri** [rsource-open-source/rsource-records#20]
```
[nodemon] starting `node dist`

[12:07:11 AM] [run] Started shard 0
[12:07:11 AM] [run] Updated presence of shard 0        
[12:07:11 AM] [run] Importing and initializing commands
[12:07:11 AM] [import] imported prefixed commands
[12:07:11 AM] [import] imported slash commands
[12:07:11 AM] [run] Starting CommandClient
[3:40:30 PM] [run] Starting InteractionCommandClient
[3:40:31 PM] [error] Error: HTTP Exception: 400 (Invalid Form Body)
Error: HTTP Exception: 400 (Invalid Form Body)
    at RestRequest.send (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\node_modules\detritus-client-rest\lib\request.js:253:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)   
    at async Client.request (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\node_modules\detritus-client-rest\lib\client.js:151:24)
    at async RestClient.bulkOverwriteApplicationCommands (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\node_modules\detritus-client\lib\rest\client.js:121:22)
    at async InteractionCommandClient.checkAndUploadCommands (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\node_modules\detritus-client\lib\interactioncommandclient.js:274:34)
    at async InteractionCommandClient.run (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\node_modules\detritus-client\lib\interactioncommandclient.js:592:13)
    at async Object.runICC (C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\dist\consoleFunctions.js:133:9)
    at async C:\Users\%USERNAME%\documents\rsource-gh\rsource-records\dist\index.js:60:9
[nodemon] clean exit - waiting for changes before restart
```

Making this here because this is rare for it to actually error.

**Comment by insyri** [comment]
fixed in following commit
